//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsWarehouse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Dostawcy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dostawcy()
        {
            this.Kartoteki = new HashSet<Kartoteki>();
        }
    
        public int Id_Dostawcy { get; set; }
        [Required(ErrorMessage = "Podaj nazwê dostawcy")]
        [StringLength(50, ErrorMessage = "Maksymalnie 50 znaków")]
        public string Nazwa { get; set; }
        [StringLength(50, ErrorMessage = "Maksymalnie 50 znaków")]
        public string Miejscowosc { get; set; }
        [StringLength(6, ErrorMessage = "Maksymalnie 6 znaków")]
        public string Kod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kartoteki> Kartoteki { get; set; }
    }
}
