//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsWarehouse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kartoteki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kartoteki()
        {
            this.Przyjecia = new HashSet<Przyjecia>();
            this.Wydania = new HashSet<Wydania>();
            this.Zamowienia = new HashSet<Zamowienia>();
        }
    
        public int Id_Kartoteki { get; set; }
        [Required(ErrorMessage = "Podaj nazwê czêœci")]
        [StringLength(50, ErrorMessage = "Maksymalnie 50 znaków")]
        public string Nazwa { get; set; }
        [Required(ErrorMessage = "Podaj stan")]
        public int Stan { get; set; }
        [Required(ErrorMessage = "Podaj miejsce sk³adowania")]
        [StringLength(50, ErrorMessage = "Maksymalnie 50 znaków")]
        public string Miejsce { get; set; }
        public int Id_JM { get; set; }
        public Nullable<int> Id_Dostawcy { get; set; }
        [Required(ErrorMessage = "Podaj kod kartoteki")]
        [StringLength(50, ErrorMessage = "Maksymalnie 50 znaków")]
        public string Kod { get; set; }
    
        public virtual Dostawcy Dostawcy { get; set; }
        public virtual JM JM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Przyjecia> Przyjecia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wydania> Wydania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienia> Zamowienia { get; set; }
    }
}
