//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsWarehouse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MagazynDBEntities : DbContext
    {
        public MagazynDBEntities()
            : base("name=MagazynDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dostawcy> Dostawcy { get; set; }
        public virtual DbSet<Dzialy> Dzialy { get; set; }
        public virtual DbSet<JM> JM { get; set; }
        public virtual DbSet<Kartoteki> Kartoteki { get; set; }
        public virtual DbSet<MPK> MPK { get; set; }
        public virtual DbSet<Osoby> Osoby { get; set; }
        public virtual DbSet<Przyjecia> Przyjecia { get; set; }
        public virtual DbSet<Wydania> Wydania { get; set; }
        public virtual DbSet<Zamowienia> Zamowienia { get; set; }
    }
}
