//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartsWarehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wydania
    {
        public int Id_Wydania { get; set; }
       // public int Ilosc { get; set; }
        public Nullable<System.DateTime> Data_Wydania { get; set; }
        public Nullable<int> Id_MPK { get; set; }
        public int Id_Osoby { get; set; }
        public int Id_Kartoteki { get; set; }
    
        public virtual Kartoteki Kartoteki { get; set; }
        public virtual MPK MPK { get; set; }
        public virtual Osoby Osoby { get; set; }
    }
}
